export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// Related to Profile 

export const FETCH_DOCTOR_PROFILE = 'FETCH_DOCTOR_PROFILE';